### ISSUE TITLE
Please change repository name

### ISSUE THREAD

**Issue by makigumo** [MiSTer-devel/Arcade-PenguinKunWars_MiSTer#2]
Hi and thanks for the core.
Could you please change the repository name to `Arcade-${name}_MiSTer`, i.e. `Arcade-PenguinKunWars_MiSTer`, which is the standard for arcade cores.
Then you can add it to https://github.com/MiSTer-devel/Main_MiSTer/wiki/Arcade-Cores-List and it will be automatically picked up by the update script.

**Comment by MacroFPGA** [comment]
Renamed - I usually get the name wrong somewhere along the line!
